# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
